### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by JimSleezus** [shysaur/QLWindowsApps#1]
Sorry for being dumb.

**Comment by shysaur** [comment]
1. Download the latest version from https://github.com/shysaur/QLWindowsApps/releases. You want the first file that ends with ".pkg"
2. Open the .pkg file you downloaded (if it says that the file cannot be opened, hold the ctrl button, click on the .pkg file, and select Open from the drop down menu)
3. Follow the instructions to install the plugin: click continue twice, accept the license agreement, click "Install", type your password, click "install software", and then click close
4. Done!

Note that this plugin does not install in the Applications folder. The installer will place it in /Library/QuickLook.
