### ISSUE TITLE
how to uninstall

### ISSUE THREAD

**Issue by Lumysia** [shysaur/QLWindowsApps#4]
Hi, is there a way to uninstall it cleanly please?
Thank you for your reply.

**Comment by shysaur** [comment]
It is enough to delete the two bundles `QLWindowsApps.qlgenerator` and `WindowsAppsImporter.mdimporter` from the library they have been installed in.

By default, the first bundle is installed in `/Library/QuickLook`, and the second bundle is installed in `/Library/Spotlight`. If you chose to install only for your user instead, the bundles are found in your user's library instead, but inside the same subdirectory (therefore `/Users/.../Library/QuickLook` and `/Users/.../Library/Spotlight`).

No other files are installed, so this is enough for a clean uninstall.
